/**
 * @file
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator.
 * No need to edit this file.
 */

#include <signal.h>
#include <alcore/alptr.h>
#include <alcommon/albroker.h>
#include <alcommon/almodule.h>
#include <alcommon/albrokermanager.h>
#include <alcommon/altoolsmain.h>


#include "oru_walk.h"




#ifdef ORU_WALK_IS_REMOTE_OFF // shared library

# ifdef _WIN32
    #define ALCALL __declspec(dllexport)
# else
    #define ALCALL
# endif

#else // standalone executable
    #define ALCALL
#endif // ORU_WALK_IS_REMOTE_OFF



#ifdef __cplusplus
extern "C"
{
#endif


ALCALL int _createModule( AL::ALPtr<AL::ALBroker> pBroker )
{
  // init broker with the main broker instance
  // from the parent executable
  AL::ALBrokerManager::setInstance(pBroker->fBrokerManager.lock());
  AL::ALBrokerManager::getInstance()->addBroker(pBroker);


  AL::ALModule::createModule<oru_walk>( pBroker, "oru_walk" );


  return 0;
}

ALCALL int _closeModule(  )
{
  return 0;
}

# ifdef __cplusplus
}
# endif


#ifdef ORU_MODULE_IS_REMOTE_ON
    #error Remote operation is not supported for this module!
#endif // ORU_MODULE_IS_REMOTE_ON
